"use strict";

Object.defineProperty(exports, "__esModule", {
	value: true
});

function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }

var $filterNullChildren = function $filterNullChildren(children) {
	return children.filter(function (child) {
		return child != null;
	});
};

exports.default = function (data, opt) {
	var View = opt.View,
	    Text = opt.Text,
	    Image = opt.Image,
	    Navigator = opt.Navigator,
	    Location = opt.Location,
	    LineChart = opt.LineChart;

	Object.assign(data, { "$str99383117": "2D", "$str20991862": "3D", "$str18851041": "2DIMAX", "$str59177128": "3DIMAX", "$str5281295": "评分：", "$str29445149": "想看：", "$str39188802": "分", "$str99604689": "人", "$str64159237": "场次：", "$str9797829": "上映：", "$str89122576": "ok" });return new View({ style: {}, attr: {}, children: $filterNullChildren([data.errCode === 0 && data.data ? new View({ style: {}, attr: { "class": "result" }, children: $filterNullChildren([new View({ style: {}, attr: { "class": "header" }, children: $filterNullChildren([new Text({ style: {}, attr: { "content": "购买电影票" }, children: $filterNullChildren([]) })]) }), new View({ style: {}, attr: { "class": "movie-cell" }, children: $filterNullChildren([new Image({ style: {}, attr: { "class": "poster", "src": data.data.img }, children: $filterNullChildren([]) }), new View({ style: {}, attr: { "class": "movie-info" }, children: $filterNullChildren([new View({ style: {}, attr: { "class": "title" }, children: $filterNullChildren([new Text({ style: {}, attr: { "class": "name", "content": data.data.movie_name }, children: $filterNullChildren([]) }), data.data.version === data.$str99383117 ? new Image({ style: {}, attr: { "class": "tag", "src": "./images/2D.png" }, children: $filterNullChildren([]) }) : null, data.data.version === data.$str20991862 ? new Image({ style: {}, attr: { "class": "tag", "src": "./images/3D.png" }, children: $filterNullChildren([]) }) : null, data.data.version === data.$str18851041 ? new Image({ style: {}, attr: { "class": "longtag", "src": "./images/2DIMAX.png" }, children: $filterNullChildren([]) }) : null, data.data.version === data.$str59177128 ? new Image({ style: {}, attr: { "class": "longtag", "src": "./images/3DIMAX.png" }, children: $filterNullChildren([]) }) : null]) }), new View({ style: {}, attr: { "class": "detail" }, children: $filterNullChildren([new Text({ style: {}, attr: { "class": "gray", "content": data.data.hasReleased ? data.$str5281295 : data.$str29445149 }, children: $filterNullChildren([]) }), data.data.hasReleased && data.data.movie_score ? new Text({ style: {}, attr: { "class": "orange", "content": data.data.movie_score + data.$str39188802 }, children: $filterNullChildren([]) }) : data.data.hasReleased ? new Text({ style: {}, attr: { "class": "gray", "content": "暂无" }, children: $filterNullChildren([]) }) : data.data.movie_expect_num ? new Text({ style: {}, attr: { "class": "orange", "content": data.data.movie_expect_num + data.$str99604689 }, children: $filterNullChildren([]) }) : new Text({ style: {}, attr: { "class": "gray", "content": "暂无" }, children: $filterNullChildren([]) })]) }), new View({ style: {}, attr: { "class": "detail" }, children: $filterNullChildren([new Text({ style: {}, attr: { "class": "gray", "content": "类型：" }, children: $filterNullChildren([]) })].concat(_toConsumableArray((data.data.movie_type || []).map(function (item, index) {
							return new View({ style: {}, attr: {}, children: $filterNullChildren([index > 0 ? new Text({ style: {}, attr: { "class": "border" }, children: $filterNullChildren([]) }) : null, new Text({ style: {}, attr: { "class": "value", "content": item }, children: $filterNullChildren([]) })]) });
						})), [!data.data.movie_type || data.data.movie_type && !data.data.movie_type.length ? new Text({ style: {}, attr: { "class": "gray", "content": "暂无" }, children: $filterNullChildren([]) }) : null])) }), new View({ style: {}, attr: { "class": "detail" }, children: $filterNullChildren([new Text({ style: {}, attr: { "class": "gray", "content": "主演：" }, children: $filterNullChildren([]) })].concat(_toConsumableArray((data.data.movie_actors || []).map(function (item, index) {
							return new View({ style: {}, attr: {}, children: $filterNullChildren([index > 0 ? new Text({ style: {}, attr: { "class": "border" }, children: $filterNullChildren([]) }) : null, new Text({ style: {}, attr: { "class": "value", "content": item }, children: $filterNullChildren([]) })]) });
						})), [!data.data.movie_actors.length ? new Text({ style: {}, attr: { "class": "gray", "content": "暂无" }, children: $filterNullChildren([]) }) : null])) }), new View({ style: {}, attr: { "class": "detail" }, children: $filterNullChildren([new Text({ style: {}, attr: { "class": "gray", "content": data.data.hasReleased ? data.$str64159237 : data.$str9797829 }, children: $filterNullChildren([]) }), data.data.hasReleased && data.data.movie_number ? new Text({ style: {}, attr: { "class": "value", "content": data.data.movie_city + "共" + data.data.movie_number + "场" }, children: $filterNullChildren([]) }) : data.data.hasReleased ? new Text({ style: {}, attr: { "class": "gray", "content": data.data.movie_city + "今日暂无排片" }, children: $filterNullChildren([]) }) : data.data.movie_release_time ? new Text({ style: {}, attr: { "class": "value", "content": data.data.movie_release_time }, children: $filterNullChildren([]) }) : new Text({ style: {}, attr: { "class": "gray", "content": "暂无" }, children: $filterNullChildren([]) })]) }), data.data.movie_price ? new View({ style: {}, attr: { "class": "detail last" }, children: $filterNullChildren([new Text({ style: {}, attr: { "class": "gray", "content": "价格：" }, children: $filterNullChildren([]) }), new Text({ style: {}, attr: { "class": "value", "content": data.data.movie_price + "元起" }, children: $filterNullChildren([]) })]) }) : null]) })]) })]) }) : new View({ style: {}, attr: { "class": "no-result-wrapper" }, children: $filterNullChildren([data.errMsg !== data.$str89122576 ? new Text({ style: {}, attr: { "class": "no-result", "content": data.errMsg }, children: $filterNullChildren([]) }) : new Text({ style: {}, attr: { "class": "no-result", "content": "未查询到" + data.query + "的相关信息" }, children: $filterNullChildren([]) })]) })]) });
};